### ISSUE TITLE
Speed dial tiles issues

### ISSUE THREAD

**Issue by pierreporte** [OtterBrowser/otter-browser#1137]
Issue present in 0b5cc495b92a6675b26e87b22045866d8e2b08d7.

I encountered several misbehaviours related to the speed dial tiles:

1. When adding a new tiles, it is impossible to select an URL using the completion menu that appears after something is typed. The selection of the URL is only possible when using the menu appearing when clicking the arrow at the right of the text field or when typing it directly.
2. When adding a tile pointing to an about:xyz page (the issue exists for all special pages but only if the tile is **created** with an about: page), 3 problems appear:
    * the generated tile is blank (screenshot below),
    * clicking on the tile with the standard click-button opens a blank page with “about:xyz” in the URL field and hitting Enter in the URL field does not load the about:xyz page (although a middle click on the tile opens the about:xyz page successfuly),
    * the edition dialog box for the tile is unusable because the OK button does nothing in this case (it works for normal tiles).

![selection_520](https://cloud.githubusercontent.com/assets/2029853/14944162/c07497d2-0feb-11e6-8f14-2a1ae812d445.png)

**Comment by pierreporte** [comment]
Commits d6c65a415c78d33f331c3bd741fdac00c895af29 and 39505556c55d3d938a734a4cd207586be1459f91 fixes my second point.

There is a new issue that was not present at the time I opened this one. Now, when a tile points to an about:xyz page and when it is reloaded, there is a spinner but it never stops. The background stays blank or whatever it was before, like a website if the tile URL was changed to about:xyz before reloading it. It should be blank or have a big icon (like Opera 12 did) instead.

I don’t remember this, but I managed to make the browser crash with the Speed dial. It doesn’t closes itself immediately but make the fans rotating at their maximum speed for several minutes and eventually makes the computer lag before closing if the process is not killed before. There is also a glitch. How I do it:

1. Create several tiles (crash happens with more than 2). It is not URL-dependant.
2. Right-click on a tile (not the first). There is now very often a blue frame around the selected one, but also around the very first one.
3. Click on the empty space to make the context menu disappear. The frame around the first tile is still there (or appears at that moment).
4. Click somewhere and hover the first tile to try to make the frame disappear.
5. Redo this from point 2 for several other tiles (including the first). The browser will eventually crash.

It is not very precise but it seems quite different every time and only this broad scheme seems to reproduce.

**Comment by Chocimier** [comment]
@pierreporte, except for crash with hovering tiles, what i can't reproduce all is fixed now.
Are you still able to crash browser? Can you provide backtrace? What OS and Qt version you use?

**Comment by pierreporte** [comment]
Using an up to date Archlinux with Qt 5.7.0 and Otter cb8e5ad25fb7b2dd43882f6c6c8e75c96b09f7e7, I am now unable to crash Otter this way. There is still the infinite spinner issue (see screencast below) with new tiles created after the update.

Typical backtrace trying to crash the browser:

```
$ otter-browser
[1105/212710:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
No language dictionaries for the language: "fr"
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
```

Though, the glitch is still present. I made a capture with VLC (converted into GIF with ffmpeg) to show how it looks like. The quality is shit, the animation is really laggy, and the cursor is invisible, but I couldn’t do better.

![capture_crop](https://cloud.githubusercontent.com/assets/2029853/20033543/dc792b1e-a3a2-11e6-862c-1196a9de2f4b.gif)

**Comment by Chocimier** [comment]
Animation is enough to show problem, thanks for it.
It is not at all glitch. The non-hover rectangle marks keyboard focus. You can move it with arrows, hide by clicking at "a" point and show by cliking at "b" point. 
However I agree it is a bit confusing, we will try to improve that. Also infinite spinner will be fixed.
![screenshot_20161110_231741](https://cloud.githubusercontent.com/assets/2065803/20196871/fd39a31c-a79c-11e6-9043-8bf146780ad9.png)
